version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  # unit-test:
  #   executor:
  #     name: node/default
  #     tag: '13.14'
  #   steps:
  #     - checkout
  #     - node/install-packages
  #     - run:
  #         command: npm run unit-test

  # integration-test:
  #   docker:
  #     - image: 'cimg/base:stable'
  #   steps:
  #     - checkout
  #     - run: npm run integration-test

  publish-prod:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          command: |
            curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash
            sudo apt-get update
            sudo apt-get install build-essential checkinstall libssl-dev
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
            sudo apt-get install expect
            sudo apt-get install nodejs-legacy
            sudo apt-get install npm
            sudo npm install
            nvm install node
            ./script.exp

workflows:
  node-tests:
    jobs:
      - publish-prod
      #- unit-test
      #- integration-test